server:
  port: 8001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userservice
    username: root
    password: Saiteja@123
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect